const productos = [
  {
    id: 1,
    producto: "bandeja lyon",
    precio: 1500,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 2,
    producto: "picador amsterdam",
    precio: 1000,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 3,
    producto: "picador esfera tricolor",
    precio: 1850,
    categoria: "parafernalia",
    oferta: true,
  },
  {
    id: 4,
    producto: "pipa madera",
    precio: 700,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 5,
    producto: "pipa dibujo con tapa",
    precio: 900,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 6,
    producto: "sauver",
    precio: 1000,
    categoria: "parafernalia",
    oferta: true,
  },
  {
    id: 7,
    producto: "pipa spiderman",
    precio: 1000,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 8,
    producto: "papel ocb premium",
    precio: 700,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 9,
    producto: "papel celulosa zeuz",
    precio: 900,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 10,
    producto: "clipper grande",
    precio: 1500,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 11,
    producto: "papel hornet transparente",
    precio: 1100,
    categoria: "parafernalia",
    oferta: true,
  },
  {
    id: 12,
    producto: "picador de madera eco",
    precio: 500,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 13,
    producto: "picador aluminio radioactivo",
    precio: 2200,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 14,
    producto: "pipa pirex m calavera",
    precio: 1100,
    categoria: "parafernalia",
    oferta: false,
  },
  {
    id: 15,
    producto: "cenicero raw",
    precio: 700,
    categoria: "parafernalia",
    oferta: false,
  },
];
